export const stackData =
  [
    { src: "/htmlIcon.svg", name: "HTML" },
    { src: "/cssIcon.svg", name: "CSS" },
    { src: "/jsIcon.svg", name: "JavaScript" },
    { src: "/typescriptIcon.svg", name: "TypeScript" },
    { src: "/reactIcon.svg", name: "React" },
    // { src: "/reactIcon.svg", name: "React-Native" },
    { src: "/nextjsIcon.svg", name: "Next.Js" },
    { src: "/reduxIcon.svg", name: "Redux" },
    // { src: "/sassIcon.svg", name: "Sass" },
    { src: "/tailwindIcon.svg", name: "Tailwind" },
    { src: "/nodejsIcon.svg", name: "Node.Js" },
    { src: "/expressjsIcon.svg", name: "Express" },
    { src: "/mongodbIcon.svg", name: "Mongo DB" },
    { src: "/web3Icon.svg", name: "Web3" },
    { src: "/awsIcon.svg", name: "AWS" },
    // { src: "/firebaseIcon.svg", name: "Firebase" },
    { src: "/gitIcon.svg", name: "Git" },
    { src: "/githubIcon.svg", name: "Github" },
    { src: "/npmIcon.svg", name: "npm" },
    // { src: "/dockerIcon.svg", name: "Docker" },
    { src: "/java.svg", name: "Java" },
    { src: "/pythonIcon.svg", name: "Python" },
    // { src: "/figmaIcon.svg", name: "Figma" },
    // { src: "/adobexdIcon.svg", name: "Adobe XD" },
  ];

export const projectsData = [
  {
    name: "De-Pay",
    description: "De-Pay is a decentralized application that facilitates any company or individual to pay the salary of their employees in ethereum with just a click of a button",
    src: "/DE-Pay.png",
    liveLink: "https://de-pay.vercel.app/",
    githubLink: "https://github.com/Abhiragk17/DE-PAY",
  },
  {
    name: "Imagify",
    description: "Imagify is a Full stack AI powered Image generation and sharing platform where a user can create any image just by simply providing its descripton.",
    src: "/Imagify.png",
    liveLink: "https://imaggify.netlify.app/",
    githubLink: "https://github.com/Abhiragk17/Imagify",
  },
  {
    name: "Artisumm",
    description: "An Article summerizer web application using react Js , TailWind CSS and Article Extractor and Summarizer API",
    src: "/ArtiSumm.png",
    liveLink: "https://artisumm.netlify.app/",
    githubLink: "https://github.com/Abhiragk17/Article-summarizer",
  },
]
